# Generated by Django 3.0.10 on 2021-01-28 02:48

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('mobile_number', models.CharField(blank=True, max_length=13)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_login', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_photo', models.ImageField(blank=True, upload_to=app.models.user_directory_path)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('kadiv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='parents',
            fields=[
                ('parent_email', models.CharField(max_length=160, primary_key=True, serialize=False)),
                ('parent_name', models.CharField(max_length=100)),
                ('parent_mobile', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='students',
            fields=[
                ('nis_student', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_student', models.CharField(max_length=100)),
                ('pob_student', models.CharField(max_length=20)),
                ('dob_student', models.DateField(default=django.utils.timezone.now)),
                ('add_student', models.TextField(blank=True)),
                ('photo_student', models.ImageField(upload_to=app.models.student_directory_path)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='app.parents')),
            ],
        ),
    ]
