# Generated by Django 3.0.10 on 2021-01-28 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadRecord',
            new_name='uploadrecords',
        ),
    ]
