# Generated by Django 3.0.10 on 2021-01-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210128_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadrecords',
            old_name='upload_by',
            new_name='uploaded_by',
        ),
        migrations.RenameField(
            model_name='uploadrecords',
            old_name='upload_date',
            new_name='uploaded_date',
        ),
    ]
