# Generated by Django 3.0.10 on 2021-01-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210128_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadrecords',
            name='file_name',
            field=models.CharField(default=1, max_length=160),
            preserve_default=False,
        ),
    ]
