# Generated by Django 3.0.10 on 2021-02-06 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_fees'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('updated_date', models.DateField(default=django.utils.timezone.now)),
                ('bill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bill_types')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students')),
            ],
        ),
        migrations.DeleteModel(
            name='fees',
        ),
    ]
