# Generated by Django 3.0.10 on 2021-02-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210206_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='bill_type',
            field=models.CharField(choices=[('S', 'Uang Bulanan'), ('P', 'Uang Pangkal'), ('L', 'Lain-Lain')], max_length=1),
        ),
    ]
