# Generated by Django 3.0.10 on 2021-02-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210222_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='sex_student',
            field=models.CharField(choices=[('P', 'Perempuan'), ('L', 'Laki-Laki')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
