# Generated by Django 3.0.10 on 2021-02-24 09:05

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_students_sex_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='plps',
            fields=[
                ('plp_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('plp_name', models.CharField(max_length=20)),
                ('rapor', models.FileField(upload_to=app.models.rapor_directory_path)),
                ('plp_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
