# Generated by Django 3.0.10 on 2021-02-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_plps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plps',
            old_name='rapor',
            new_name='plp_rapor',
        ),
    ]
