# Generated by Django 3.0.10 on 2021-02-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210225_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='class_student',
            field=models.TextField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI')], max_length=4),
        ),
        migrations.AddField(
            model_name='students',
            name='sem_student',
            field=models.TextField(blank=True, choices=[('1', 'Ganjil'), ('2', 'Genap')], max_length=1),
        ),
    ]
