# Generated by Django 3.0.10 on 2021-02-25 02:02

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210225_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plps',
            name='plp_rapor',
        ),
        migrations.CreateModel(
            name='plp_rapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapor_section', models.CharField(max_length=100)),
                ('section_file', models.FileField(upload_to=app.models.rapor_directory_path)),
                ('plp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plps')),
            ],
        ),
    ]
