# Generated by Django 3.0.10 on 2021-02-25 02:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210225_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='plps',
            name='plp_rapor',
            field=models.FileField(blank=True, upload_to=app.models.rapor_directory_path),
        ),
        migrations.DeleteModel(
            name='plp_rapor',
        ),
    ]
