# Generated by Django 3.0.10 on 2021-02-25 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210225_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='plprecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_plp', models.DateField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('plp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plps')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students')),
            ],
        ),
    ]
