# Generated by Django 3.0.10 on 2021-02-26 20:50

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_plprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='plprecord',
            name='report_excel',
            field=models.FileField(blank=True, null=True, upload_to=app.models.rapor_directory_path),
        ),
        migrations.AddField(
            model_name='plprecord',
            name='report_result',
            field=models.FileField(blank=True, null=True, upload_to=app.models.rapor_directory_path),
        ),
    ]
