# Generated by Django 3.0.10 on 2021-02-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210227_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='class_student',
            field=models.TextField(blank=True, choices=[('1 (Satu)', 'I'), ('2 (Dua)', 'II'), ('3 (Tiga)', 'III'), ('4 (Empat)', 'IV'), ('5 (Lima)', 'V'), ('6 (Enam)', 'VI')], max_length=30),
        ),
        migrations.AlterField(
            model_name='students',
            name='sem_student',
            field=models.TextField(blank=True, choices=[('Ganjil', 'Ganjil'), ('Genap', 'Genap')], max_length=10),
        ),
    ]
