# Generated by Django 3.0.10 on 2021-02-27 23:00

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210227_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plprecord',
            name='report_excel',
            field=models.FileField(blank=True, null=True, upload_to=app.models.rapor_record_directory_path),
        ),
        migrations.AlterField(
            model_name='plprecord',
            name='report_result',
            field=models.FileField(blank=True, null=True, upload_to=app.models.rapor_record_directory_path),
        ),
        migrations.CreateModel(
            name='content_rapor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_nilai', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('plprecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.plprecord')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
