# Generated by Django 3.0.10 on 2021-03-06 07:30

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=360)),
                ('file', models.FileField(upload_to=app.models.subject_directory_path)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subjects')),
            ],
        ),
    ]
