# Generated by Django 3.0.10 on 2021-03-06 09:46

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_subject_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=app.models.bill_directory_path),
        ),
    ]
