# Generated by Django 3.0.10 on 2021-03-08 22:31

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_bills_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plps',
            name='plp_rapor',
        ),
        migrations.AddField(
            model_name='plps',
            name='plp_rapor_fq',
            field=models.FileField(blank=True, null=True, upload_to=app.models.rapor_directory_path),
        ),
        migrations.AddField(
            model_name='plps',
            name='plp_rapor_qbs',
            field=models.FileField(blank=True, null=True, upload_to=app.models.rapor_directory_path),
        ),
        migrations.AlterField(
            model_name='plps',
            name='plp_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='students',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='app.parents'),
        ),
        migrations.AlterField(
            model_name='students',
            name='photo_student',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.student_directory_path),
        ),
    ]
