# Generated by Django 3.0.10 on 2021-03-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210309_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='parent_add',
            field=models.TextField(blank=True, null=True),
        ),
    ]
