# Generated by Django 3.0.10 on 2021-03-16 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_parents_parent_add'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content_rapor',
            name='plprecord',
        ),
        migrations.AlterField(
            model_name='students',
            name='dob_student',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
