# Generated by Django 3.0.10 on 2021-03-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210316_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_rapor',
            name='plp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.plps'),
        ),
        migrations.AddField(
            model_name='content_rapor',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.students'),
        ),
    ]
