# Generated by Django 3.0.10 on 2021-03-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210316_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='plprecord',
            name='o_nilai',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='content_rapor',
        ),
    ]
