# Generated by Django 3.0.10 on 2021-03-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20210316_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='plprecord',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
