# Generated by Django 3.0.10 on 2021-03-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20210325_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plprecord',
            name='report_result',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
