# Generated by Django 3.0.10 on 2021-03-25 04:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20210325_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plprecord',
            name='report_result',
            field=models.FileField(blank=True, null=True, upload_to=app.models.rapor_record_directory_path),
        ),
    ]
