# Generated by Django 3.0.10 on 2021-03-31 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20210325_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parents',
            name='parent_mobile',
            field=models.CharField(max_length=20),
        ),
    ]
